language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - cmake
      - gfortran

script:
  - cargo build --no-default-features --features=netlib --verbose
  - cargo test --no-default-features --features=netlib --verbose

  - cargo build --no-default-features --features=openblas --verbose
  - cargo test --no-default-features --features=openblas --verbose

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    - RUSTDOC_VERSION=nightly
    - secure: etByoQAe+qULGNl7uRrY/JcfQvH/blKMN6mWvSAq+J1NQRygaT3rWqwTtf200mqeYD2DGQ46k+QFKzIKUWbdhl99bsvLD2GKMYQG0UasrQRBmj432aQCoY0QQfZwQc0RyGl3Pb04CGTwKP0UGELxncwZziXWtOrY8PxZ38ZVMHs=

notifications:
  email: false
