language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - gfortran

env:
  - PROVIDER=netlib-provider
  - PROVIDER=openblas-provider

script:
  - cargo build --no-default-features --features=$PROVIDER --verbose
  - cargo test --no-default-features --features=$PROVIDER --verbose

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    - RUSTDOC_VERSION=nightly
    - secure: etByoQAe+qULGNl7uRrY/JcfQvH/blKMN6mWvSAq+J1NQRygaT3rWqwTtf200mqeYD2DGQ46k+QFKzIKUWbdhl99bsvLD2GKMYQG0UasrQRBmj432aQCoY0QQfZwQc0RyGl3Pb04CGTwKP0UGELxncwZziXWtOrY8PxZ38ZVMHs=

notifications:
  email: false
