language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - gfortran

after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      curl https://stainless-steel.github.io/travis/update_documentation.sh | bash;
    fi

env:
  global:
    - secure: etByoQAe+qULGNl7uRrY/JcfQvH/blKMN6mWvSAq+J1NQRygaT3rWqwTtf200mqeYD2DGQ46k+QFKzIKUWbdhl99bsvLD2GKMYQG0UasrQRBmj432aQCoY0QQfZwQc0RyGl3Pb04CGTwKP0UGELxncwZziXWtOrY8PxZ38ZVMHs=

notifications:
  email: false
