language: rust
sudo: false

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

env:
  matrix:
    - FEATURE=accelerate
    - FEATURE=netlib
    - FEATURE=openblas

  global:
    - RUSTDOC_VERSION=nightly
    - secure: etByoQAe+qULGNl7uRrY/JcfQvH/blKMN6mWvSAq+J1NQRygaT3rWqwTtf200mqeYD2DGQ46k+QFKzIKUWbdhl99bsvLD2GKMYQG0UasrQRBmj432aQCoY0QQfZwQc0RyGl3Pb04CGTwKP0UGELxncwZziXWtOrY8PxZ38ZVMHs=

matrix:
  exclude:
    - os: linux
      env: FEATURE=accelerate

before_install:
  - curl https://stainless-steel.github.io/travis/install_gfortran.sh | bash

script:
  - cargo test --no-default-features --features=$FEATURE --verbose

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

notifications:
  email: false

addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - cmake
      - gfortran
