[package]
name = "liblapack-sys"
version = "0.0.15"
authors = ["Corey Richardson <corey@octayn.net>", "Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/liblapack-sys"
homepage = "https://github.com/stainless-steel/liblapack-sys"
documentation = "https://stainless-steel.github.io/liblapack-sys"
description = "The package provides bindings to the Linear Algebra PACKage."

[dependencies]
libc = "*"

[features]
default = ["openblas"]
openblas = ["openblas-blas-provider"]
netlib = ["netlib-blas-provider"]

[dependencies.openblas-blas-provider]
version = "*"
optional = true

[dependencies.netlib-blas-provider]
version = "*"
optional = true
