[package]
name = "lapack-sys"
version = "0.4.1"
authors = [
  "Andrew Straw <strawman@astraw.com>",
  "Corey Richardson <corey@octayn.net>",
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
]
license = "MIT"
repository = "https://github.com/stainless-steel/lapack-sys"
homepage = "https://github.com/stainless-steel/lapack-sys"
documentation = "https://stainless-steel.github.io/lapack-sys"
description = "The package provides bindings to the Linear Algebra PACKage."

[features]
default = ["openblas"]

accelerate = ["accelerate-provider"]
netlib = ["netlib-provider"]
openblas = ["openblas-provider"]

[dependencies]
libc = "0.2"

[dependencies.accelerate-provider]
version = "0.1"
optional = true

[dependencies.netlib-provider]
version = "0.1"
optional = true

[dependencies.openblas-provider]
version = "0.1"
optional = true
