[package]
name = "liblapack-sys"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
links = "liblapack"
build = "build.rs"

[dependencies.libblas-sys]
git = "https://github.com/stainless-steel/libblas-sys.git"
