[package]
name = "lapack-sys"
version = "0.10.1"
license = "Apache-2.0/MIT"
authors = [
  "Andrew Straw <strawman@astraw.com>",
  "Corey Richardson <corey@octayn.net>",
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
]
description = "The package provides bindings to the Linear Algebra PACKage."
documentation = "https://stainless-steel.github.io/lapack-sys"
homepage = "https://github.com/stainless-steel/lapack-sys"
repository = "https://github.com/stainless-steel/lapack-sys"

[features]
default = ["openblas"]

accelerate = ["accelerate-provider"]
netlib = ["netlib-provider"]
openblas = ["openblas-provider"]

[dependencies]
libc = "0.2"

[dependencies.accelerate-provider]
version = "0.2"
optional = true

[dependencies.netlib-provider]
version = "0.3"
optional = true

[dependencies.openblas-provider]
version = "0.3"
optional = true
