[package]
name = "lapack-sys"
version = "0.3.1"
authors = ["Corey Richardson <corey@octayn.net>", "Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/lapack-sys"
homepage = "https://github.com/stainless-steel/lapack-sys"
documentation = "https://stainless-steel.github.io/lapack-sys"
description = "The package provides bindings to the Linear Algebra PACKage."

[dependencies]
libc = "*"

[features]
default = ["openblas"]
openblas = ["openblas-provider"]
netlib = ["netlib-provider"]
accelerate = ["accelerate-provider"]

[dependencies.openblas-provider]
version = "0.1"
optional = true

[dependencies.netlib-provider]
version = "0.1"
optional = true

[dependencies.accelerate-provider]
version = "0.1.1"
optional = true
